name: Actualizador Automatico IPTV

on:
  schedule:
    - cron: '0 */4 * * *' # Se ejecuta solo cada 4 horas
  workflow_dispatch: # Te deja probarlo con un botón manual

jobs:
  actualizar-lista:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Ejecutar script de Python
      run: python EL_7_TELEVISION.py

    - name: Guardar cambios en el repositorio
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add EL_7_TELEVISION.m3u
        git commit -m "Lista IPTV actualizada" || echo "Sin cambios"
        git push
