name: Actualizar Canal 7 Fijo

on:
  schedule:
    - cron: '0 0 * * *' # Se ejecuta de forma automática una vez al día
  workflow_dispatch: # Activa el botón gris para correrlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v4

    - name: Configurar entorno de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Configurar credenciales de Git primero
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@://github.com"

    - name: Ejecutar script extractor
      run: python grabber.py

    - name: Guardar cambios en el repositorio
      run: |
        # Git busca el archivo solo DESPUÉS de que Python ya lo guardó en la carpeta
        if [ -f "canal7mendoza.m3u" ]; then
          git add canal7mendoza.m3u
          git diff-index --quiet HEAD || git commit -m "Lista M3U con URL de YouTube corregida"
          git push
        else
          echo "El archivo canal7mendoza.m3u no se encontró. Saltando guardado."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

