name: Actualizar Canal 7 por API

on:
  schedule:
    # Se ejecuta automáticamente cada 2 horas
    - cron: '0 */2 * * *'
  workflow_dispatch: # Activar manualmente mediante el botón en GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v4

    - name: Configurar entorno de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependencias requeridas
      run: |
        pip install requests

    - name: Consultar API de El Siete y armar M3U
      run: python grabber.py

    - name: Guardar cambios de forma segura en GitHub
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@://github.com"
        
        # El comando touch previene el error 'fatal: pathspec' creando un archivo si falta
        touch canal7mendoza.m3u
        git add canal7mendoza.m3u
        
        # Sube la actualización y termina en verde si no hay cambios bruscos
        git commit -m "Renovación de enlace usando API de la web" || true
        git push || true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

