name: Actualizador Automatico IPTV

on:
  schedule:
    # Se despierta solo cada 3 horas exactas a renovar tu token real
    - cron: '0 */3 * * *'
  workflow_dispatch: # Permite darle Play manual

permissions:
  contents: write

jobs:
  actualizar:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4.2.2

      - name: Configurar Python en el servidor
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.10'

      - name: Instalar el extractor yt-dlp actualizado
        run: |
          pip install --upgrade pip
          pip install yt-dlp

      - name: Ejecutar el script extractor de token real
        run: python servidor_iptv.py

      - name: Guardar y subir los cambios con el token real a GitHub
        run: |
          git config --global user.name "GitHub Actions Robot"
          git config --global user.email "actions@github.com"
          git add EL_7_TELEVISION.m3u
          git commit -m "Token real generado en automatico por el robot" || exit 0
          git push
