name: Actualizar Canal 7 M3U

on:
  schedule:
    # Se ejecuta de manera automática cada 4 horas
    - cron: '0 */4 * * *'
  workflow_dispatch: # Permite ejecutar el script de forma manual cuando quieras

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-python: '3.x'

    - name: Instalar dependencias
      run: |
        pip install requests

    - name: Ejecutar script extractor
      run: python grabber.py

    - name: Subir cambios al repositorio con token interno
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add canal7mendoza.m3u
        # Solo hace commit si el archivo cambió para no generar basura
        git diff-index --quiet HEAD || git commit -m "Lista M3U actualizada automáticamente"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
